In [2]:
import numpy as np
data = np.array([
    [53,500],
    [22,45],
    [5,50],
    [3,0],
    [7,160],
    [1,47],
    [9,580],
    [0,600],
    [0,155],
    [5,50]
])
age= np.array([53,22,5,3,7,1,9,0,0,5])
income = np.array([500,45,50,0,160,47,580,600,155,50])
print(age)

[53 22  5  3  7  1  9  0  0  5]


In [22]:
def Euclidean(a,b):
    return np.sqrt(np.sum((a-b)**2))
def Manhattan(a,b):
    return np.sum(np.abs(a-b))
def Minkowski(a,b,p=3):
    return np.power(np.sum(np.abs(a-b)**p),1/p)
def Chebyshev(a,b):
    return np.max(np.abs(a-b))

In [23]:
def dissimilarity_matrix(data,dis_fun,p=None):
    n = data.shape[0]
    matrix = np.zeros((n,n))
    for i in range (n):
        for j in range (i,n) :
            if dis_fun == Minkowski:
                dissimilarity = Minkowski(data[i],data[j],p=3)
            else:
                dissimilarity = dis_fun(data[i],data[j])
            matrix[j,i]=dissimilarity
    return matrix


In [24]:
#FOR AGE AND INCOME
Euclidean_matrix = dissimilarity_matrix(data,Euclidean)
Manhattan_matrix = dissimilarity_matrix(data,Manhattan)
Minkowski_matrix = dissimilarity_matrix(data,Minkowski,p=3)
Chebyshev_matrix = dissimilarity_matrix(data,Chebyshev)

In [30]:
print("Euclidean \n",Euclidean_matrix)
print("Manhattan \n",Manhattan_matrix)
print("Minkowski \n",Minkowski_matrix)
print("Chebyshev \n",Chebyshev_matrix)

Euclidean 
 [[  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [456.05482127   0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [452.55275936  17.72004515   0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [502.49378106  48.84669897  50.03998401   0.           0.
    0.           0.           0.           0.           0.        ]
 [343.09765374 115.97413505 110.01818032 160.04999219   0.
    0.           0.           0.           0.           0.        ]
 [455.97478     21.09502311   5.          47.04253395 113.15917992
    0.           0.           0.           0.           0.        ]
 [ 91.30169768 535.15792062 530.01509412 580.03103365 420.00476188
  533.06003414   0.           0.           0.           0.        ]
 [113.17685276 555.43586488 550.0227268  600.00749995 440.0556783
  553.00090416  2

In [31]:
#FOR AGE
Euclidean_matrix_age = dissimilarity_matrix(age,Euclidean)
Manhattan_matrix_age = dissimilarity_matrix(age,Manhattan)
Minkowski_matrix_age = dissimilarity_matrix(age,Minkowski,p=3)
Chebyshev_matrix_age = dissimilarity_matrix(age,Chebyshev)

In [32]:
print("Euclidean \n",Euclidean_matrix_age)
print("Manhattan \n",Manhattan_matrix_age)
print("Minkowski \n",Minkowski_matrix_age)
print("Chebyshev \n",Chebyshev_matrix_age)

Euclidean 
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [31.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [48. 17.  0.  0.  0.  0.  0.  0.  0.  0.]
 [50. 19.  2.  0.  0.  0.  0.  0.  0.  0.]
 [46. 15.  2.  4.  0.  0.  0.  0.  0.  0.]
 [52. 21.  4.  2.  6.  0.  0.  0.  0.  0.]
 [44. 13.  4.  6.  2.  8.  0.  0.  0.  0.]
 [53. 22.  5.  3.  7.  1.  9.  0.  0.  0.]
 [53. 22.  5.  3.  7.  1.  9.  0.  0.  0.]
 [48. 17.  0.  2.  2.  4.  4.  5.  5.  0.]]
Manhattan 
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [31.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [48. 17.  0.  0.  0.  0.  0.  0.  0.  0.]
 [50. 19.  2.  0.  0.  0.  0.  0.  0.  0.]
 [46. 15.  2.  4.  0.  0.  0.  0.  0.  0.]
 [52. 21.  4.  2.  6.  0.  0.  0.  0.  0.]
 [44. 13.  4.  6.  2.  8.  0.  0.  0.  0.]
 [53. 22.  5.  3.  7.  1.  9.  0.  0.  0.]
 [53. 22.  5.  3.  7.  1.  9.  0.  0.  0.]
 [48. 17.  0.  2.  2.  4.  4.  5.  5.  0.]]
Minkowski 
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [31.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [48. 17.  0.  0

In [33]:
#FOR INCOME
Euclidean_matrix_income = dissimilarity_matrix(income,Euclidean)
Manhattan_matrix_income = dissimilarity_matrix(income,Manhattan)
Minkowski_matrix_income = dissimilarity_matrix(income,Minkowski,p=3)
Chebyshev_matrix_income = dissimilarity_matrix(income,Chebyshev)

In [34]:
print("Euclidean \n",Euclidean_matrix_income)
print("Manhattan \n",Manhattan_matrix_income)
print("Minkowski \n",Minkowski_matrix_income)
print("Chebyshev \n",Chebyshev_matrix_income)

Euclidean 
 [[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [455.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [450.   5.   0.   0.   0.   0.   0.   0.   0.   0.]
 [500.  45.  50.   0.   0.   0.   0.   0.   0.   0.]
 [340. 115. 110. 160.   0.   0.   0.   0.   0.   0.]
 [453.   2.   3.  47. 113.   0.   0.   0.   0.   0.]
 [ 80. 535. 530. 580. 420. 533.   0.   0.   0.   0.]
 [100. 555. 550. 600. 440. 553.  20.   0.   0.   0.]
 [345. 110. 105. 155.   5. 108. 425. 445.   0.   0.]
 [450.   5.   0.  50. 110.   3. 530. 550. 105.   0.]]
Manhattan 
 [[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [455.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [450.   5.   0.   0.   0.   0.   0.   0.   0.   0.]
 [500.  45.  50.   0.   0.   0.   0.   0.   0.   0.]
 [340. 115. 110. 160.   0.   0.   0.   0.   0.   0.]
 [453.   2.   3.  47. 113.   0.   0.   0.   0.   0.]
 [ 80. 535. 530. 580. 420. 533.   0.   0.   0.   0.]
 [100. 555. 550. 600. 440. 553.  20.   0.   0.   0.]
 [345. 110. 105. 155.

In [39]:
#WEIGHTED 
def weighted_dissimilarity_matrix(data,dis_fun,weight=1,p=None):
    n = data.shape[0]
    matrix = np.zeros((n,n))
    for i in range (n):
        for j in range (i,n) :
            if dis_fun == Minkowski:
                dissimilarity = Minkowski(weight*data[i],data[j],p=3)
            else:
                dissimilarity = dis_fun(weight*data[i],data[j])
            matrix[j,i]=dissimilarity
    return matrix


In [55]:
Euclidean_matrix_w = weighted_dissimilarity_matrix(data,Euclidean,2.5)
Manhattan_matrix_w = weighted_dissimilarity_matrix(data,Manhattan,2.5)
Minkowski_matrix_w = weighted_dissimilarity_matrix(data,Minkowski,weight=2.5,p=3)
Chebyshev_matrix_w = weighted_dissimilarity_matrix(data,Chebyshev,2.5)
print("Euclidean \n",Euclidean_matrix_w)
print("Manhattan \n",Manhattan_matrix_w)
print("Minkowski \n",Minkowski_matrix_w)
print("Chebyshev \n",Chebyshev_matrix_w)

Euclidean 
 [[ 754.20173031    0.            0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [1210.05588714   75.13487872    0.            0.            0.
     0.            0.            0.            0.            0.        ]
 [1206.75442821   80.03905297   75.37406716    0.            0.
     0.            0.            0.            0.            0.        ]
 [1256.69019651  123.93647566  125.36048022    4.5           0.
     0.            0.            0.            0.            0.        ]
 [1097.20109825   67.52962313   35.42950748  160.00078125  240.2295777
     0.            0.            0.            0.            0.        ]
 [1210.16579443   84.88963423   78.84319882   47.44733923  353.38541283
    70.51595564    0.            0.            0.            0.        ]
 [ 681.28720082  469.75765028  455.01346134  580.00193965  180.20058268
   462.54567342  870.10473508    0.            0.            0.        ]
 [ 663